baseURL = "http://example.org/"
languageCode = "en-us"
title = "Yenting Chen (a.k.a JimYTC)"
theme = "ezhil"

# --------------------------------------------
# Theme specific configs from ezhil
# --------------------------------------------

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "UA-9646591-7"
# Your Disqus sortname.
# disqusShortname = "localhost"

[params]
  # Blog subtitle which appears below blog title. Supports markdown.
  subtitle = "def jimytc; puts 'Dad, Rubyist, Rails dev'; end"

  # Number of posts to show in recent posts list (Optional). Defaults to 10.
  recentPostsCount = 10

  # Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
  excludedTypes = ["page"]

  # Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
  disableDisqusTypes = ["page"]

  # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
  featherIconsCDN = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/jimytc"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jimytc"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/jim.yenting"

# Enable tags.
[taxonomies]
   tag = "tags"