## Basic Configuration
baseurl = "https://jimytc.com/"
languageCode = "en"

title = "Jim Chen"
theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "jimytc-github-io"
googleAnalytics = "UA-9646591-7"
enableRobotsTXT = true

summarylength = 30

paginate = 5

## Site Settings
[params]
    author = "Jim Chen"
    title = "Backend Engineer"
    description = "a.k.a. jimytc"
    authorimage = "/images/author-photo.png"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "jimytc"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

    # ThemeColor from original hyde
    themeColor = "theme-base-0a"

    postNavigation = false

## Social Accounts
[params.social]
    github = "jimytc"
    instagram = "jimytc"
    # xing = "<username>"
    linkedin = "yentingchen"
    twitter = "jimytc"
    facebook = "jim.yenting"
    stackoverflow = "2728942/jimytc"
    # telegram = "<username>"
    # email = "solofat@gmail.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 200
    url = "/tags/"
[[menu.main]]
    name = "Categories"
    identifier = "categories"
    weight = 300
    url = "/categories/"
# [[menu.main]]
#     name = "About"
#     identifier = "about"
#     weight = 800
#     url = "/about/"

# Enable tags.
[taxonomies]
  tag = "tags"
  category = "categories"
