name: Hugo Build and Deploy

on:
  pull_request:
    branches:
      - master
    types: [closed]
  push:
    branches:
      - master

jobs:
  if-merged:
    runs-on: unbuntu-latest
    if: github.event.pull_request.merged == true || contains(github.event.head_commit.message, '[ci force]') 
    steps:
      - run: echo PR merged!
  test:
    runs-on: unbuntu-latest
    needs: if-merged
    steps:
      - run: echo Test Passed
  finished:
    runs-on: unbuntu-latest
    needs: [if-merged, test]
    steps:
      - name: Deploy
        run: echo Finished!
